# Environment Setting

In [1]:
import pandas as pd

# Import data

In [2]:
Dominant_PATH = '../Public_Analysis/Datasets/'
doc = pd.read_csv(Dominant_PATH +'Seoul_Covid_19.csv', 
                  encoding = 'utf-8')
doc = doc.dropna(subset = ['지역'])
doc.head()

,연번,확진일,환자번호,국적,환자정보,지역,여행력,접촉력,조치사항,상태,이동경로,등록일,수정일,노출여부
0,21771,21.01.11.,NaN,NaN,NaN,성동구,NaN,기타 확진자 접촉,NaN,NaN,NaN,2021-01-12 11:17,2021-01-12 11:17,Y
1,21770,21.01.11.,NaN,NaN,NaN,금천구,NaN,기타 확진자 접촉,NaN,NaN,NaN,2021-01-12 11:17,2021-01-12 11:17,Y
2,21769,21.01.11.,NaN,NaN,NaN,기타,NaN,구로구 소재 요양병원/요양원 관련,NaN,NaN,NaN,2021-01-12 11:17,2021-01-12 11:17,Y
3,21768,21.01.11.,NaN,NaN,NaN,강서구,NaN,감염경로 조사중,NaN,NaN,NaN,2021-01-12 11:17,2021-01-12 11:17,Y
4,21767,21.01.11.,NaN,NaN,NaN,도봉구,NaN,감염경로 조사중,NaN,NaN,NaN,2021-01-12 11:17,2021-01-12 11:17,Y

# Check data

In [3]:
doc.shape

(21769, 14)

## Data insight
We need column ['확진일', '지역']

# EDA

In [4]:
doc = doc[['확진일', '지역']]
doc = doc[::-1].reset_index(drop=True)
doc

             확진일   지역
0       20.1.24.  강서구
1       20.1.30.  중랑구
2       20.1.30.  종로구
3       20.1.30.  마포구
4       20.1.31.  성북구
...          ...  ...
21764  21.01.11.  도봉구
21765  21.01.11.  강서구
21766  21.01.11.   기타
21767  21.01.11.  금천구
21768  21.01.11.  성동구

[21769 rows x 2 columns]

In [5]:
doc.groupby(['확진일', '지역']).sum()

Empty DataFrame
Columns: []
Index: [(20.08.25., 영등포구), (20.1.24., 강서구), (20.1.30., 마포구), (20.1.30., 종로구), (20.1.30., 중랑구), (20.1.31., 성북구), (20.1.31., 종로구), (20.10.01., 강남구), (20.10.01., 관악구), (20.10.01., 구로구), (20.10.01., 금천구), (20.10.01., 기타), (20.10.01., 마포구), (20.10.01., 성동구), (20.10.01., 성북구), (20.10.01., 종로구), (20.10.02., 강서구), (20.10.02., 관악구), (20.10.02., 기타), (20.10.02., 노원구), (20.10.02., 도봉구), (20.10.02., 동대문구), (20.10.02., 동작구), (20.10.02., 마포구), (20.10.02., 서초구), (20.10.02., 성동구), (20.10.02., 중랑구), (20.10.03., 강남구), (20.10.03., 강북구), (20.10.03., 관악구), (20.10.03., 구로구), (20.10.03., 기타), (20.10.03., 동대문구), (20.10.03., 동작구), (20.10.03., 마포구), (20.10.03., 용산구), (20.10.03., 은평구), (20.10.03., 중랑구), (20.10.04., 강남구), (20.10.04., 강동구), (20.10.04., 강북구), (20.10.04., 관악구), (20.10.04., 광진구), (20.10.04., 구로구), (20.10.04., 노원구), (20.10.04., 도봉구), (20.10.04., 동대문구), (20.10.04., 동작구), (20.10.04., 타시도), (20.10.05., 강북구), (20.10.05., 강서구), (20.10.05., 관악구), (20.10.05., 광진구), (20.10.05., 구로구), (20.10.05., 금천구), (20.10.05., 기타), (20.10.05., 노원구), (20.10.05., 동대문구), (20.10.05., 동작구), (20.10.05., 서초구), (20.10.05., 영등포구), (20.10.05., 용산구), (20.10.05., 중랑구), (20.10.05., 타시도), (20.10.06., 강남구), (20.10.06., 강북구), (20.10.06., 관악구), (20.10.06., 광진구), (20.10.06., 기타), (20.10.06., 노원구), (20.10.06., 도봉구), (20.10.06., 동대문구), (20.10.06., 마포구), (20.10.06., 서초구), (20.10.06., 성동구), (20.10.06., 송파구), (20.10.06., 영등포구), (20.10.06., 용산구), (20.10.06., 중랑구), (20.10.06., 타시도), (20.10.07., 강동구), (20.10.07., 관악구), (20.10.07., 구로구), (20.10.07., 기타), (20.10.07., 노원구), (20.10.07., 도봉구), (20.10.07., 동대문구), (20.10.07., 서대문구), (20.10.07., 서초구), (20.10.07., 성동구), (20.10.07., 용산구), (20.10.07., 은평구), (20.10.08., 강남구), (20.10.08., 관악구), (20.10.08., 광진구), (20.10.08., 기타), (20.10.08., 노원구), (20.10.08., 동대문구), (20.10.08., 동작구), (20.10.08., 서초구), ...]

[4262 rows x 0 columns]

## Data insight
We want data construction with 
index : 지역, column : 확진일

In [6]:
Region = doc['지역']
Region_list = list(Region.unique())
Region_list

['강서구',
 '중랑구',
 '종로구',
 '마포구',
 '성북구',
 '타시도',
 '송파구',
 '서대문구',
 '성동구',
 '강남구',
 '서초구',
 '구로구',
 '강동구',
 '은평구',
 '관악구',
 '금천구',
 '노원구',
 '동작구',
 '양천구',
 '동대문구',
 '광진구',
 '영등포구',
 '도봉구',
 '용산구',
 '강북구',
 '중구',
 '기타']

In [7]:
Dates = doc['확진일']
Dates_list = list(Dates.unique())
Dates_list

['20.1.24.',
 '20.1.30.',
 '20.1.31.',
 '20.2.2.',
 '20.2.5.',
 '20.2.6.',
 '20.2.7.',
 '20.2.16.',
 '20.2.19.',
 '20.2.20.',
 '20.2.21.',
 '20.2.22.',
 '20.2.23.',
 '20.2.26.',
 '20.2.24.',
 '20.2.25.',
 '20.2.27.',
 '20.2.28.',
 '20.2.29.',
 '20.3.1.',
 '20.3.2.',
 '20.3.3.',
 '20.3.4.',
 '20.3.5.',
 '20.3.6.',
 '20.3.7.',
 '20.3.8.',
 '20.3.9.',
 '20.3.10.',
 '20.3.11.',
 '20.3.12.',
 '20.3.13.',
 '20.3.14.',
 '20.3.15.',
 '20.3.16.',
 '20.3.17.',
 '20.3.18.',
 '20.3.19.',
 '20.3.20.',
 '20.3.21.',
 '20.3.22.',
 '20.3.23.',
 '20.3.24.',
 '20.3.25.',
 '20.3.26.',
 '20.3.27.',
 '20.3.28.',
 '20.3.29.',
 '20.3.30.',
 '20.3.31.',
 '20.4.01.',
 '20.4.02.',
 '20.4.3.',
 '20.4.04.',
 '20.4.05.',
 '20.4.06.',
 '20.4.07.',
 '20.4.08.',
 '20.4.09.',
 '20.4.10.',
 '20.4.11.',
 '20.4.12.',
 '20.4.13.',
 '20.4.14.',
 '20.4.15.',
 '20.4.16.',
 '20.4.17.',
 '20.4.18.',
 '20.4.19.',
 '20.4.20.',
 '20.4.21.',
 '20.4.24.',
 '20.4.27.',
 '20.4.30.',
 '20.5.01.',
 '20.5.02.',
 '20.5.08.',
 '20.5.09.',
 '20.5.9.',
 '20.5.10.',
 '20.5.11.',
 '20.5.12.',
 '20.5.13.',
 '20.5.14.',
 '20.5.15.',
 '20.5.16.',
 '20.5.17.',
 '20.5.18.',
 '20.5.19.',
 '20.5.20.',
 '20.5.21.',
 '20.5.22.',
 '20.5.23.',
 '20.5.24.',
 '20.5.25.',
 '20.5.26.',
 '20.5.27.',
 '20.5.28.',
 '20.5.29.',
 '20.5.30.',
 '20.5.31.',
 '20.6.01.',
 '20.6.02.',
 '20.6.03.',
 '20.6.04.',
 '20.6.05.',
 '20.6.06.',
 '20.6.07.',
 '20.6.08.',
 '20.6.09.',
 '20.6.10.',
 '20.6.11.',
 '20.6.12.',
 '20.6.13.',
 '20.6.14.',
 '20.6.15.',
 '20.6.16.',
 '20.6.17.',
 '20.6.18.',
 '20.6.19.',
 '20.6.20.',
 '20.6.21.',
 '20.6.22.',
 '20.6.23.',
 '20.6.24.',
 '20.6.25.',
 '20.6.26.',
 '20.6.27.',
 '20.6.28.',
 '20.6.29.',
 '20.6.30.',
 '20.7.01.',
 '20.7.02.',
 '20.7.03.',
 '20.7.04.',
 '20.7.05.',
 '20.7.06.',
 '20.7.07.',
 '20.7.08.',
 '20.7.09.',
 '20.7.10.',
 '20.7.11.',
 '20.7.12.',
 '20.7.13.',
 '20.7.14.',
 '20.7.15.',
 '20.7.16.',
 '20.7.17.',
 '20.7.18.',
 '20.7.19.',
 '20.7.20.',
 '20.7.21.',
 '20.7.22.',
 '20.7.23.',
 '20.7.24.',
 '20.7.25.',
 '20.7.26.',
 '20.7.27.',
 '20.7.28.',
 '20.7.29.',
 '20.7.30.',
 '20.7.31.',
 '20.8.1.',
 '20.8.2.',
 '20.8.3.',
 '20.8.4.',
 '20.8.5.',
 '20.8.6.',
 '20.8.7.',
 '20.8.8.',
 '20.8.9.',
 '20.8.10.',
 '20.8.11.',
 '20.8.12.',
 '20.8.13.',
 '20.8.14.',
 '20.8.15.',
 '20.8.16.',
 '20.8.17.',
 '20.8.18.',
 '20.8.19.',
 '20.8.20.',
 '20.8.21.',
 '20.8.22.',
 '20.8.23.',
 '20.8.24.',
 '20.8.25.',
 '20.8.26.',
 '20.8.27.',
 '20.8.28.',
 '20.8.29.',
 '20.9.01.',
 '20.8.30.',
 '20.8.31.',
 '20.9.02.',
 '20.9.03.',
 '20.9.04.',
 '20.9.05.',
 '20.9.06.',
 '20.9.07.',
 '20.9.08.',
 '20.9.09.',
 '20.9.10.',
 '20.9.11.',
 '20.9.12.',
 '20.9.13.',
 '20.9.14.',
 '20.9.15.',
 '20.9.16.',
 '20.9.17.',
 '20.9.18.',
 '20.9.19.',
 '20.9.20.',
 '20.9.21.',
 '20.9.22.',
 '20.9.23.',
 '20.9.24.',
 '20.9.25.',
 '20.9.26.',
 '20.9.27.',
 '20.9.28.',
 '20.9.29.',
 '20.9.30.',
 '20.10.01.',
 '20.10.02.',
 '20.10.03.',
 '20.10.04.',
 '20.10.05.',
 '20.10.06.',
 '20.10.07.',
 '20.10.08.',
 '20.10.09.',
 '20.10.10.',
 '20.10.11.',
 '20.10.12.',
 '20.10.13.',
 '20.10.14.',
 '20.10.15.',
 '20.10.16.',
 '20.10.17.',
 '20.10.18.',
 '20.10.19.',
 '20.10.20.',
 '20.10.21.',
 '20.10.22.',
 '20.10.23.',
 '20.10.24.',
 '20.10.25.',
 '20.10.26.',
 '20.10.27.',
 '20.10.28.',
 '20.10.29.',
 '20.10.30.',
 '20.10.31.',
 '20.11.01.',
 '20.11.02.',
 '20.11.03.',
 '20.11.04.',
 '20.11.05.',
 '20.11.06.',
 '20.11.07.',
 '20.11.08.',
 '20.11.09.',
 '20.11.10.',
 '20.11.11.',
 '20.11.12.',
 '20.11.13.',
 '20.11.14.',
 '20.11.15.',
 '20.11.16.',
 '20.08.25.',
 '20.11.17.',
 '20.11.18.',
 '20.11.19.',
 '20.11.20.',
 '20.11.21.',
 '20.11.22.',
 '20.11.23.',
 '20.11.24.',
 '20.11.25.',
 '20.11.26.',
 '20.11.27.',
 '20.11.28.',
 '20.11.29.',
 '20.11.30.',
 '20.12.01.',
 '20.12.02.',
 '20.12.03.',
 '20.12.04.',
 '20.12.05.',
 '20.12.06.',
 '20.12.07.',
 '20.12.08.',
 '20.12.09.',
 '20.12.10.',
 '20.12.11.',
 '20.12.12.',
 '20.12.13.',
 '20.12.14.',
 '20.12.15.',
 '20.12.16.',
 '20.12.17.',
 '20.12.18.',
 '20.12.19.',
 '20.12.20.',
 '20.12.21.',
 '20.12.22.',
 '20.12.23.',
 '20.12.24.',
 '20.12.25.',
 '20.12.26.',
 '20.12.27.',
 '20.12.28.',
 '20.12.29.',
 '20.12.30.',
 '20.12.31.',
 '21.01.01.',
 '21.01.02.',
 '21.01.03.',
 '21.01.04.',
 '21.01.05.',
 '21.01.06.',
 '21.01.07.',
 '21.01.08.',
 '21.01.09.',
 '21.01.10.',
 '21.01.11.']

## Data insight
We need dataFrame construction like <br>
index / column 20.03.01  20.04.01 <br>
성동구 <br>
금천구 <br>
강서구 <br>
도봉구 <br>
은평구 <br>
서대문구 <br>
종로구 <br>

In [8]:
Seoul_final = pd.DataFrame({'Region' : Region_list})
Seoul_final

   Region
0     강서구
1     중랑구
2     종로구
3     마포구
4     성북구
5     타시도
6     송파구
7    서대문구
8     성동구
9     강남구
10    서초구
11    구로구
12    강동구
13    은평구
14    관악구
15    금천구
16    노원구
17    동작구
18    양천구
19   동대문구
20    광진구
21   영등포구
22    도봉구
23    용산구
24    강북구
25     중구
26     기타

## Data insight
How about make data frame with summing Series by Time line

In [9]:
doc_copy = doc[doc['확진일']==Dates_list[0]]
doc_copy

        확진일   지역
0  20.1.24.  강서구

In [10]:
day = pd.DataFrame({'Region' : Region_list,
                    Dates_list[0] : 0})
day

   Region  20.1.24.
0     강서구         0
1     중랑구         0
2     종로구         0
3     마포구         0
4     성북구         0
5     타시도         0
6     송파구         0
7    서대문구         0
8     성동구         0
9     강남구         0
10    서초구         0
11    구로구         0
12    강동구         0
13    은평구         0
14    관악구         0
15    금천구         0
16    노원구         0
17    동작구         0
18    양천구         0
19   동대문구         0
20    광진구         0
21   영등포구         0
22    도봉구         0
23    용산구         0
24    강북구         0
25     중구         0
26     기타         0

In [11]:
for i in range(len(doc_copy)):
    for ind in range(len(day)) : 
        if day.loc[ind, 'Region'] == doc_copy.loc[i, '지역'] : 
            day.loc[ind, Dates_list[0]] += 1
day

   Region  20.1.24.
0     강서구         1
1     중랑구         0
2     종로구         0
3     마포구         0
4     성북구         0
5     타시도         0
6     송파구         0
7    서대문구         0
8     성동구         0
9     강남구         0
10    서초구         0
11    구로구         0
12    강동구         0
13    은평구         0
14    관악구         0
15    금천구         0
16    노원구         0
17    동작구         0
18    양천구         0
19   동대문구         0
20    광진구         0
21   영등포구         0
22    도봉구         0
23    용산구         0
24    강북구         0
25     중구         0
26     기타         0

In [12]:
Seoul_final = pd.merge(Seoul_final, day)
Seoul_final

   Region  20.1.24.
0     강서구         1
1     중랑구         0
2     종로구         0
3     마포구         0
4     성북구         0
5     타시도         0
6     송파구         0
7    서대문구         0
8     성동구         0
9     강남구         0
10    서초구         0
11    구로구         0
12    강동구         0
13    은평구         0
14    관악구         0
15    금천구         0
16    노원구         0
17    동작구         0
18    양천구         0
19   동대문구         0
20    광진구         0
21   영등포구         0
22    도봉구         0
23    용산구         0
24    강북구         0
25     중구         0
26     기타         0

In [13]:
doc_copy = doc[doc['확진일']==Dates_list[1]]
doc_copy = doc_copy.reset_index(drop= True)
doc_copy

        확진일   지역
0  20.1.30.  중랑구
1  20.1.30.  종로구
2  20.1.30.  마포구

In [14]:
day = pd.DataFrame({'Region' : Region_list, Dates_list[1] : 0})
day

   Region  20.1.30.
0     강서구         0
1     중랑구         0
2     종로구         0
3     마포구         0
4     성북구         0
5     타시도         0
6     송파구         0
7    서대문구         0
8     성동구         0
9     강남구         0
10    서초구         0
11    구로구         0
12    강동구         0
13    은평구         0
14    관악구         0
15    금천구         0
16    노원구         0
17    동작구         0
18    양천구         0
19   동대문구         0
20    광진구         0
21   영등포구         0
22    도봉구         0
23    용산구         0
24    강북구         0
25     중구         0
26     기타         0

In [15]:
for i in range(len(doc_copy)):
    for ind in range(len(day)) : 
        if day.loc[ind, 'Region'] == doc_copy.loc[i, '지역'] : 
            day.loc[ind, Dates_list[1]] += 1
day

   Region  20.1.30.
0     강서구         0
1     중랑구         1
2     종로구         1
3     마포구         1
4     성북구         0
5     타시도         0
6     송파구         0
7    서대문구         0
8     성동구         0
9     강남구         0
10    서초구         0
11    구로구         0
12    강동구         0
13    은평구         0
14    관악구         0
15    금천구         0
16    노원구         0
17    동작구         0
18    양천구         0
19   동대문구         0
20    광진구         0
21   영등포구         0
22    도봉구         0
23    용산구         0
24    강북구         0
25     중구         0
26     기타         0

In [16]:
Seoul_final = pd.merge(Seoul_final, day)
Seoul_final

   Region  20.1.24.  20.1.30.
0     강서구         1         0
1     중랑구         0         1
2     종로구         0         1
3     마포구         0         1
4     성북구         0         0
5     타시도         0         0
6     송파구         0         0
7    서대문구         0         0
8     성동구         0         0
9     강남구         0         0
10    서초구         0         0
11    구로구         0         0
12    강동구         0         0
13    은평구         0         0
14    관악구         0         0
15    금천구         0         0
16    노원구         0         0
17    동작구         0         0
18    양천구         0         0
19   동대문구         0         0
20    광진구         0         0
21   영등포구         0         0
22    도봉구         0         0
23    용산구         0         0
24    강북구         0         0
25     중구         0         0
26     기타         0         0

# Making for-loop of EDA

In [17]:
Seoul_final = pd.DataFrame({'Region' : Region_list})
for j in range(len(Dates_list)) : 
    doc_copy = doc[doc['확진일']==Dates_list[j]]
    doc_copy = doc_copy.reset_index(drop= True)
    day = pd.DataFrame({'Region' : Region_list, Dates_list[j] : 0})
    for i in range(len(doc_copy)):
        for ind in range(len(day)) : 
            if day.loc[ind, 'Region'] == doc_copy.loc[i, '지역'] : 
                day.loc[ind, Dates_list[j]] += 1
    Seoul_final = pd.merge(Seoul_final, day)
Seoul_final

,Region,20.1.24.,20.1.30.,20.1.31.,20.2.2.,20.2.5.,20.2.6.,20.2.7.,20.2.16.,20.2.19.,...,21.01.02.,21.01.03.,21.01.04.,21.01.05.,21.01.06.,21.01.07.,21.01.08.,21.01.09.,21.01.10.,21.01.11.
0,강서구,1,0,0,0,0,0,0,0,0,...,12,14,4,22,14,9,9,3,4,3
1,중랑구,0,1,0,0,0,0,0,0,0,...,3,14,11,7,10,9,4,7,6,11
2,종로구,0,1,2,0,0,0,0,2,1,...,5,3,5,12,5,2,4,9,4,6
3,마포구,0,1,0,0,0,0,0,0,0,...,5,8,5,5,6,7,9,3,3,9
4,성북구,0,0,1,0,1,0,0,0,0,...,8,9,8,14,16,16,6,6,2,2
5,타시도,0,0,0,1,0,0,1,0,0,...,6,6,10,11,7,11,15,12,12,2
6,송파구,0,0,0,0,1,0,0,0,0,...,11,8,11,19,8,16,15,10,10,4
7,서대문구,0,0,0,0,0,1,0,0,0,...,4,2,7,10,14,11,7,12,6,2
8,성동구,0,0,0,0,0,0,0,0,1,...,0,8,4,4,4,4,1,5,4,14
9,강남구,0,0,0,0,0,0,0,0,0,...,4,11,8,7,14,8,10,9,7,9
10,서초구,0,0,0,0,0,0,0,0,0,...,9,4,4,11,7,3,7,3,3,4
11,구로구,0,0,0,0,0,0,0,0,0,...,10,7,10,19,7,9,5,8,2,8
12,강동구,0,0,0,0,0,0,0,0,0,...,13,7,11,3,10,8,4,10,7,8
13,은평구,0,0,0,0,0,0,0,0,0,...,5,3,7,12,16,7,12,9,8,12
14,관악구,0,0,0,0,0,0,0,0,0,...,4,7,6,7,5,5,9,8,2,6
15,금천구,0,0,0,0,0,0,0,0,0,...,4,5,7,3,6,3,1,1,2,1
16,노원구,0,0,0,0,0,0,0,0,0,...,12,10,6,12,8,5,2,6,8,12
17,동작구,0,0,0,0,0,0,0,0,0,...,6,10,8,9,4,4,9,7,10,7
18,양천구,0,0,0,0,0,0,0,0,0,...,13,9,8,11,11,9,10,13,6,6
19,동대문구,0,0,0,0,0,0,0,0,0,...,7,6,13,12,5,4,7,4,13,12
20,광진구,0,0,0,0,0,0,0,0,0,...,4,12,6,5,15,3,6,7,5,2
21,영등포구,0,0,0,0,0,0,0,0,0,...,8,14,13,8,8,10,15,8,4,1
22,도봉구,0,0,0,0,0,0,0,0,0,...,4,10,4,12,6,9,6,5,6,8
23,용산구,0,0,0,0,0,0,0,0,0,...,3,0,4,5,2,9,1,2,2,3
24,강북구,0,0,0,0,0,0,0,0,0,...,18,14,15,7,16,2,8,6,2,6
25,중구,0,0,0,0,0,0,0,0,0,...,0,2,1,4,4,5,1,1,1,3
26,기타,0,0,0,0,0,0,0,0,0,...,23,123,7,8,69,2,4,13,2,6

In [18]:
Seoul_final = Seoul_final.set_index('Region')
Seoul_final.head()

,20.1.24.,20.1.30.,20.1.31.,20.2.2.,20.2.5.,20.2.6.,20.2.7.,20.2.16.,20.2.19.,20.2.20.,...,21.01.02.,21.01.03.,21.01.04.,21.01.05.,21.01.06.,21.01.07.,21.01.08.,21.01.09.,21.01.10.,21.01.11.
Region,,,,,,,,,,,,,,,,,,,,,
강서구,1,0,0,0,0,0,0,0,0,0,...,12,14,4,22,14,9,9,3,4,3
중랑구,0,1,0,0,0,0,0,0,0,0,...,3,14,11,7,10,9,4,7,6,11
종로구,0,1,2,0,0,0,0,2,1,3,...,5,3,5,12,5,2,4,9,4,6
마포구,0,1,0,0,0,0,0,0,0,0,...,5,8,5,5,6,7,9,3,3,9
성북구,0,0,1,0,1,0,0,0,0,0,...,8,9,8,14,16,16,6,6,2,2

In [19]:
Seoul_final = Seoul_final.cumsum(axis = 1)
Seoul_final = Seoul_final.drop(['타시도', '기타'])
Seoul_final

,20.1.24.,20.1.30.,20.1.31.,20.2.2.,20.2.5.,20.2.6.,20.2.7.,20.2.16.,20.2.19.,20.2.20.,...,21.01.02.,21.01.03.,21.01.04.,21.01.05.,21.01.06.,21.01.07.,21.01.08.,21.01.09.,21.01.10.,21.01.11.
Region,,,,,,,,,,,,,,,,,,,,,
강서구,1,1,1,1,1,1,1,1,1,1,...,1362,1376,1380,1402,1416,1425,1434,1437,1441,1444
중랑구,0,1,1,1,1,1,1,1,1,1,...,810,824,835,842,852,861,865,872,878,889
종로구,0,1,3,3,3,3,3,5,6,9,...,412,415,420,432,437,439,443,452,456,462
마포구,0,1,1,1,1,1,1,1,1,1,...,707,715,720,725,731,738,747,750,753,762
성북구,0,0,1,1,2,2,2,2,2,2,...,831,840,848,862,878,894,900,906,908,910
송파구,0,0,0,0,1,1,1,1,1,1,...,1143,1151,1162,1181,1189,1205,1220,1230,1240,1244
서대문구,0,0,0,0,0,1,1,1,1,1,...,528,530,537,547,561,572,579,591,597,599
성동구,0,0,0,0,0,0,0,0,1,2,...,466,474,478,482,486,490,491,496,500,514
강남구,0,0,0,0,0,0,0,0,0,1,...,944,955,963,970,984,992,1002,1011,1018,1027
서초구,0,0,0,0,0,0,0,0,0,0,...,842,846,850,861,868,871,878,881,884,888
구로구,0,0,0,0,0,0,0,0,0,0,...,618,625,635,654,661,670,675,683,685,693
강동구,0,0,0,0,0,0,0,0,0,0,...,591,598,609,612,622,630,634,644,651,659
은평구,0,0,0,0,0,0,0,0,0,0,...,803,806,813,825,841,848,860,869,877,889
관악구,0,0,0,0,0,0,0,0,0,0,...,1035,1042,1048,1055,1060,1065,1074,1082,1084,1090
금천구,0,0,0,0,0,0,0,0,0,0,...,327,332,339,342,348,351,352,353,355,356
노원구,0,0,0,0,0,0,0,0,0,0,...,836,846,852,864,872,877,879,885,893,905
동작구,0,0,0,0,0,0,0,0,0,0,...,850,860,868,877,881,885,894,901,911,918
양천구,0,0,0,0,0,0,0,0,0,0,...,708,717,725,736,747,756,766,779,785,791
동대문구,0,0,0,0,0,0,0,0,0,0,...,673,679,692,704,709,713,720,724,737,749
광진구,0,0,0,0,0,0,0,0,0,0,...,473,485,491,496,511,514,520,527,532,534
영등포구,0,0,0,0,0,0,0,0,0,0,...,716,730,743,751,759,769,784,792,796,797
도봉구,0,0,0,0,0,0,0,0,0,0,...,579,589,593,605,611,620,626,631,637,645
용산구,0,0,0,0,0,0,0,0,0,0,...,426,426,430,435,437,446,447,449,451,454
강북구,0,0,0,0,0,0,0,0,0,0,...,473,487,502,509,525,527,535,541,543,549
중구,0,0,0,0,0,0,0,0,0,0,...,287,289,290,294,298,303,304,305,306,309

# Changing column name by Time Series

In [20]:
Seoul_final.columns

Index(['20.1.24.', '20.1.30.', '20.1.31.', '20.2.2.', '20.2.5.', '20.2.6.',
       '20.2.7.', '20.2.16.', '20.2.19.', '20.2.20.',
       ...
       '21.01.02.', '21.01.03.', '21.01.04.', '21.01.05.', '21.01.06.',
       '21.01.07.', '21.01.08.', '21.01.09.', '21.01.10.', '21.01.11.'],
      dtype='object', length=327)

In [21]:
Seoul_final.columns[0]

'20.1.24.'

In [22]:
String = Seoul_final.columns[0].split('.')[0:3]
String

['20', '1', '24']

In [23]:
if len(String[1]) == 1:
    String[1] = '0' + String[1]
else : 
    String[1]
String

['20', '01', '24']

In [24]:
if String[0] == '20' :
    String += ['2020']
else :
    String += ['2021']
String = String[1:]
String

['01', '24', '2020']

In [25]:
list(String)

['01', '24', '2020']

In [26]:
String = '/'.join(String)
String
type(String)

str

In [27]:
len(Seoul_final.columns)

327

# For-loop of Changing column name

In [28]:
New_columns = list()
for i in range(len(Seoul_final.columns)) :
    String = Seoul_final.columns[i].split('.')[0:3]
    if len(String[1]) == 1:
        String[1] = '0' + String[1]
    else : 
        String[1]
    
    if String[0] == '20' :
        String += ['2020']
    else :
        String += ['2021']
    String = String[1:]
    list(String)
    String = '/'.join(String)
    New_columns.append(String)
Seoul_final.columns = New_columns
Seoul_final.columns

Index(['01/24/2020', '01/30/2020', '01/31/2020', '02/2/2020', '02/5/2020',
       '02/6/2020', '02/7/2020', '02/16/2020', '02/19/2020', '02/20/2020',
       ...
       '01/02/2021', '01/03/2021', '01/04/2021', '01/05/2021', '01/06/2021',
       '01/07/2021', '01/08/2021', '01/09/2021', '01/10/2021', '01/11/2021'],
      dtype='object', length=327)

In [29]:
Seoul_final

,01/24/2020,01/30/2020,01/31/2020,02/2/2020,02/5/2020,02/6/2020,02/7/2020,02/16/2020,02/19/2020,02/20/2020,...,01/02/2021,01/03/2021,01/04/2021,01/05/2021,01/06/2021,01/07/2021,01/08/2021,01/09/2021,01/10/2021,01/11/2021
Region,,,,,,,,,,,,,,,,,,,,,
강서구,1,1,1,1,1,1,1,1,1,1,...,1362,1376,1380,1402,1416,1425,1434,1437,1441,1444
중랑구,0,1,1,1,1,1,1,1,1,1,...,810,824,835,842,852,861,865,872,878,889
종로구,0,1,3,3,3,3,3,5,6,9,...,412,415,420,432,437,439,443,452,456,462
마포구,0,1,1,1,1,1,1,1,1,1,...,707,715,720,725,731,738,747,750,753,762
성북구,0,0,1,1,2,2,2,2,2,2,...,831,840,848,862,878,894,900,906,908,910
송파구,0,0,0,0,1,1,1,1,1,1,...,1143,1151,1162,1181,1189,1205,1220,1230,1240,1244
서대문구,0,0,0,0,0,1,1,1,1,1,...,528,530,537,547,561,572,579,591,597,599
성동구,0,0,0,0,0,0,0,0,1,2,...,466,474,478,482,486,490,491,496,500,514
강남구,0,0,0,0,0,0,0,0,0,1,...,944,955,963,970,984,992,1002,1011,1018,1027
서초구,0,0,0,0,0,0,0,0,0,0,...,842,846,850,861,868,871,878,881,884,888
구로구,0,0,0,0,0,0,0,0,0,0,...,618,625,635,654,661,670,675,683,685,693
강동구,0,0,0,0,0,0,0,0,0,0,...,591,598,609,612,622,630,634,644,651,659
은평구,0,0,0,0,0,0,0,0,0,0,...,803,806,813,825,841,848,860,869,877,889
관악구,0,0,0,0,0,0,0,0,0,0,...,1035,1042,1048,1055,1060,1065,1074,1082,1084,1090
금천구,0,0,0,0,0,0,0,0,0,0,...,327,332,339,342,348,351,352,353,355,356
노원구,0,0,0,0,0,0,0,0,0,0,...,836,846,852,864,872,877,879,885,893,905
동작구,0,0,0,0,0,0,0,0,0,0,...,850,860,868,877,881,885,894,901,911,918
양천구,0,0,0,0,0,0,0,0,0,0,...,708,717,725,736,747,756,766,779,785,791
동대문구,0,0,0,0,0,0,0,0,0,0,...,673,679,692,704,709,713,720,724,737,749
광진구,0,0,0,0,0,0,0,0,0,0,...,473,485,491,496,511,514,520,527,532,534
영등포구,0,0,0,0,0,0,0,0,0,0,...,716,730,743,751,759,769,784,792,796,797
도봉구,0,0,0,0,0,0,0,0,0,0,...,579,589,593,605,611,620,626,631,637,645
용산구,0,0,0,0,0,0,0,0,0,0,...,426,426,430,435,437,446,447,449,451,454
강북구,0,0,0,0,0,0,0,0,0,0,...,473,487,502,509,525,527,535,541,543,549
중구,0,0,0,0,0,0,0,0,0,0,...,287,289,290,294,298,303,304,305,306,309

In [30]:
Seoul_final.reset_index()

,Region,01/24/2020,01/30/2020,01/31/2020,02/2/2020,02/5/2020,02/6/2020,02/7/2020,02/16/2020,02/19/2020,...,01/02/2021,01/03/2021,01/04/2021,01/05/2021,01/06/2021,01/07/2021,01/08/2021,01/09/2021,01/10/2021,01/11/2021
0,강서구,1,1,1,1,1,1,1,1,1,...,1362,1376,1380,1402,1416,1425,1434,1437,1441,1444
1,중랑구,0,1,1,1,1,1,1,1,1,...,810,824,835,842,852,861,865,872,878,889
2,종로구,0,1,3,3,3,3,3,5,6,...,412,415,420,432,437,439,443,452,456,462
3,마포구,0,1,1,1,1,1,1,1,1,...,707,715,720,725,731,738,747,750,753,762
4,성북구,0,0,1,1,2,2,2,2,2,...,831,840,848,862,878,894,900,906,908,910
5,송파구,0,0,0,0,1,1,1,1,1,...,1143,1151,1162,1181,1189,1205,1220,1230,1240,1244
6,서대문구,0,0,0,0,0,1,1,1,1,...,528,530,537,547,561,572,579,591,597,599
7,성동구,0,0,0,0,0,0,0,0,1,...,466,474,478,482,486,490,491,496,500,514
8,강남구,0,0,0,0,0,0,0,0,0,...,944,955,963,970,984,992,1002,1011,1018,1027
9,서초구,0,0,0,0,0,0,0,0,0,...,842,846,850,861,868,871,878,881,884,888
10,구로구,0,0,0,0,0,0,0,0,0,...,618,625,635,654,661,670,675,683,685,693
11,강동구,0,0,0,0,0,0,0,0,0,...,591,598,609,612,622,630,634,644,651,659
12,은평구,0,0,0,0,0,0,0,0,0,...,803,806,813,825,841,848,860,869,877,889
13,관악구,0,0,0,0,0,0,0,0,0,...,1035,1042,1048,1055,1060,1065,1074,1082,1084,1090
14,금천구,0,0,0,0,0,0,0,0,0,...,327,332,339,342,348,351,352,353,355,356
15,노원구,0,0,0,0,0,0,0,0,0,...,836,846,852,864,872,877,879,885,893,905
16,동작구,0,0,0,0,0,0,0,0,0,...,850,860,868,877,881,885,894,901,911,918
17,양천구,0,0,0,0,0,0,0,0,0,...,708,717,725,736,747,756,766,779,785,791
18,동대문구,0,0,0,0,0,0,0,0,0,...,673,679,692,704,709,713,720,724,737,749
19,광진구,0,0,0,0,0,0,0,0,0,...,473,485,491,496,511,514,520,527,532,534
20,영등포구,0,0,0,0,0,0,0,0,0,...,716,730,743,751,759,769,784,792,796,797
21,도봉구,0,0,0,0,0,0,0,0,0,...,579,589,593,605,611,620,626,631,637,645
22,용산구,0,0,0,0,0,0,0,0,0,...,426,426,430,435,437,446,447,449,451,454
23,강북구,0,0,0,0,0,0,0,0,0,...,473,487,502,509,525,527,535,541,543,549
24,중구,0,0,0,0,0,0,0,0,0,...,287,289,290,294,298,303,304,305,306,309

In [34]:
Seoul_final.to_csv("../Public_Analysis/Datasets/Seoul_final.csv")

# Final total code

In [35]:
import pandas as pd
Dominant_PATH = '../Public_Analysis/Datasets/'
doc = pd.read_csv(Dominant_PATH + 'Seoul_Covid_19.csv', 
                  encoding = 'utf-8')
doc = doc.dropna(subset = ['지역'])
doc = doc[['확진일', '지역']]
doc = doc[::-1].reset_index(drop=True)
Region = doc['지역']
Region_list = list(Region.unique())
Region_list
Dates = doc['확진일']
Dates_list = list(Dates.unique())

Seoul_final = pd.DataFrame({'Region' : Region_list})
for j in range(len(Dates_list)) : 
    doc_copy = doc[doc['확진일']==Dates_list[j]]
    doc_copy = doc_copy.reset_index(drop= True)
    day = pd.DataFrame({'Region' : Region_list, Dates_list[j] : 0})
    for i in range(len(doc_copy)):
        for ind in range(len(day)) : 
            if day.loc[ind, 'Region'] == doc_copy.loc[i, '지역'] : 
                day.loc[ind, Dates_list[j]] += 1
    Seoul_final = pd.merge(Seoul_final, day)
    
Seoul_final = Seoul_final.set_index('Region')
Seoul_final = Seoul_final.cumsum(axis = 1)
Seoul_final = Seoul_final.drop(['타시도', '기타'])

In [36]:
New_columns = list()
for i in range(len(Seoul_final.columns)) :
    String = Seoul_final.columns[i].split('.')[0:3]
    if len(String[1]) == 1:
        String[1] = '0' + String[1]
    else : 
        String[1]
    
    if String[0] == '20' :
        String += ['2020']
    else :
        String += ['2021']
    String = String[1:]
    list(String)
    String = '/'.join(String)
    New_columns.append(String)
Seoul_final.columns = New_columns

# Making function

In [37]:
import pandas as pd

def change_column_name(DataFrame) :
    New_columns = list()
    for i in range(len(DataFrame.columns)) :
        String = DataFrame.columns[i].split('.')[0:3]
        if len(String[1]) == 1:
            String[1] = '0' + String[1]
        else : 
            String[1]
    
        if String[0] == '20' :
            String += ['2020']
        else :
            String += ['2021']
        String = String[1:]
        list(String)
        String = '/'.join(String)
        New_columns.append(String)
    DataFrame.columns = New_columns
    return DataFrame

def create_data_frame(filename) : 
    doc = pd.read_csv(Dominant_PATH + filename, encoding = 'utf-8')
    
    doc = doc.dropna(subset = ['지역'])
    doc = doc[['확진일', '지역']]
    doc = doc[::-1].reset_index(drop=True)
    
    Region = doc['지역']
    Region_list = list(Region.unique())
    Dates = doc['확진일']
    Dates_list = list(Dates.unique())
    
    Seoul_final = pd.DataFrame({'Region' : Region_list})
    for j in range(len(Dates_list)) : 
        doc_copy = doc[doc['확진일']==Dates_list[j]]
        doc_copy = doc_copy.reset_index(drop= True)
        day = pd.DataFrame({'Region' : Region_list, Dates_list[j] : 0})
        for i in range(len(doc_copy)):
            for ind in range(len(day)) : 
                if day.loc[ind, 'Region'] == doc_copy.loc[i, '지역'] : 
                    day.loc[ind, Dates_list[j]] += 1
        Seoul_final = pd.merge(Seoul_final, day)
    
    Seoul_final = Seoul_final.set_index('Region')
    Seoul_final = Seoul_final.cumsum(axis = 1)
    Seoul_final = Seoul_final.drop(['타시도', '기타'])
    return Seoul_final

In [38]:
Dominant_PATH = '../Public_Analysis/Datasets/'
Seoul_confirmed = create_data_frame('Seoul_Covid_19.csv')
Seoul_confirmed
Seoul_confirmed_final = change_column_name(Seoul_confirmed)
Seoul_confirmed_final
Seoul_confirmed_final.to_csv("../Public_Analysis/Datasets/Seoul_final.csv")